### ISSUE TITLE
Installation folder

### ISSUE THREAD

**Issue by stanjosh** [whogben/gd_credentials#1]
Plugins usually are installed to the addons/ directory but yours goes to the root directory instead. The user must create the addons/ directory manually, if it does not exist.

Fix: Create directories addons/gd_credentials/ and move files there

**Comment by whogben** [comment]
Thanks for telling me! From what I understand, I need to use the root Godot project dir as the root dir for Git, and put the license and the readme in the top level folder.

However, this seems like a broken way to do things because A) I can't have multiple addon projects at once, or else they'll git conflict since they're all going to have the project root as their git root, and B) the files LICENSE and README.md will be overlapping, so if someone installs 2 addons, the second addon will overwrite the license and readme of the first.

Any chance you know what the solution is? For example, when I try to install your addon, I'm getting this issue:
![image](https://github.com/user-attachments/assets/0a847e8c-4c8c-4a95-811a-e5951b20676e)

It seems like this does not allow developing (or safely installing) more than 1 addon per project without their readme and license getting stripped?

It seems like a workable approach might be to skip the addons folder completely, and make my asset install in it's own named folder in the project root - but I can see why people wouldn't enjoy that either. I just need a solution that won't create conflicts with other addons, and having the README and LICENSE in the addons dir definitely conflicts.

**Comment by stanjosh** [comment]
In the suggested instructions for submission of an addon to the assetlib,
it says to have a redundant copy of license and readme in the folder with
the addon. And that yeah, your git files are going to be overwritten. If
you leave it all directly in root, though, while I see your point, it
breaks your paths on your scripts

**Comment by stanjosh** [comment]
Regardless, it works. It's just wonky. Maybe they'll implement a cleaner way instead of direct copying

**Comment by whogben** [comment]
This thread seems to be the latest:
https://github.com/godotengine/godot-proposals/issues/554

I'm going to try to unlist these from the addons library because I can't find a workaround for my use case at the moment (I need to have multiple addons in the same project, but I can't have multiple git repos all at the project root level, and the README/LICENSE cannot be maintained with multiple addons in one project).

If anyone needs the addon they can download from GitHub.
